# ====================== #
# ======开发环境配置====== #
# ====================== #

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/api-boot-admin?characterEncoding=utf8&serverTimezone=Asia/Shanghai
  # 配置Spring Security安全用户
  security:
    user:
      name: logging-admin
      password: admin#logserver
# ApiBoot相关配置
api:
  boot:
    logging:
      admin:
        show-console-report-log: true
        format-console-log-json: true
